<!doctype html><html lang=en><head><title>Using try/catch/finally Blocks in PowerShell · GeekyRyan</title><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=color-scheme content="light dark"><meta name=author content="Ryan Nemeth"><meta name=description content="Despite being a great language, PowerShell is not impervious to errors. Errors that occur within your code can stop it&rsquo;s execution or even cause unexpected changes in the resources that your script is managing. Learning to handle these errors gracefully is the foundation of defensive coding. Today, we&rsquo;ll take a quick look at how PowerShell handles errors with Try-Catch-Finally blocks. They allow you to gracefully handle errors and perform cleanup operations, ensuring that your script doesn&rsquo;t crash when the unexpected occurs. We&rsquo;ll then cover the differences in terminating and non-terminating errors and why you should take these into consideration when implementing error handling."><meta name=keywords content="blog,developer,personal,devops"><meta name=twitter:card content="summary"><meta name=twitter:title content="Using try/catch/finally Blocks in PowerShell"><meta name=twitter:description content="Despite being a great language, PowerShell is not impervious to errors. Errors that occur within your code can stop it’s execution or even cause unexpected changes in the resources that your script is managing. Learning to handle these errors gracefully is the foundation of defensive coding. Today, we’ll take a quick look at how PowerShell handles errors with Try-Catch-Finally blocks. They allow you to gracefully handle errors and perform cleanup operations, ensuring that your script doesn’t crash when the unexpected occurs. We’ll then cover the differences in terminating and non-terminating errors and why you should take these into consideration when implementing error handling."><meta property="og:url" content="https://rnemeth90.github.io/posts/2023-08-15-powershell-try-catch/"><meta property="og:site_name" content="GeekyRyan"><meta property="og:title" content="Using try/catch/finally Blocks in PowerShell"><meta property="og:description" content="Despite being a great language, PowerShell is not impervious to errors. Errors that occur within your code can stop it’s execution or even cause unexpected changes in the resources that your script is managing. Learning to handle these errors gracefully is the foundation of defensive coding. Today, we’ll take a quick look at how PowerShell handles errors with Try-Catch-Finally blocks. They allow you to gracefully handle errors and perform cleanup operations, ensuring that your script doesn’t crash when the unexpected occurs. We’ll then cover the differences in terminating and non-terminating errors and why you should take these into consideration when implementing error handling."><meta property="og:locale" content="en"><meta property="og:type" content="article"><meta property="article:section" content="posts"><meta property="article:published_time" content="2023-08-15T00:00:00+00:00"><meta property="article:modified_time" content="2023-08-15T00:00:00+00:00"><meta property="article:tag" content="PowerShell"><meta property="article:tag" content="Devops"><meta property="article:tag" content="Software Development"><link rel=canonical href=https://rnemeth90.github.io/posts/2023-08-15-powershell-try-catch/><link rel=preload href=/fonts/fa-brands-400.woff2 as=font type=font/woff2 crossorigin><link rel=preload href=/fonts/fa-regular-400.woff2 as=font type=font/woff2 crossorigin><link rel=preload href=/fonts/fa-solid-900.woff2 as=font type=font/woff2 crossorigin><link rel=stylesheet href=/css/coder.min.ed30115a76cdaa62f2229e973d5b1c89b2d3dd4b1d9c07a729baad06aa3b0cbe.css integrity="sha256-7TARWnbNqmLyIp6XPVscibLT3UsdnAenKbqtBqo7DL4=" crossorigin=anonymous media=screen><link rel=stylesheet href=/css/coder-dark.min.a00e6364bacbc8266ad1cc81230774a1397198f8cfb7bcba29b7d6fcb54ce57f.css integrity="sha256-oA5jZLrLyCZq0cyBIwd0oTlxmPjPt7y6KbfW/LVM5X8=" crossorigin=anonymous media=screen><link rel=icon type=image/svg+xml href=/images/favicon.svg sizes=any><link rel=icon type=image/png href=/images/favicon-32x32.png sizes=32x32><link rel=icon type=image/png href=/images/favicon-16x16.png sizes=16x16><link rel=apple-touch-icon href=/images/apple-touch-icon.png><link rel=apple-touch-icon sizes=180x180 href=/images/apple-touch-icon.png><link rel=manifest href=/site.webmanifest><link rel=mask-icon href=/images/safari-pinned-tab.svg color=#5bbad5></head><body class="preload-transitions colorscheme-auto"><div class=float-container><a id=dark-mode-toggle class=colorscheme-toggle><i class="fa-solid fa-adjust fa-fw" aria-hidden=true></i></a></div><main class=wrapper><nav class=navigation><section class=container><a class=navigation-title href=https://rnemeth90.github.io/>GeekyRyan
</a><input type=checkbox id=menu-toggle>
<label class="menu-button float-right" for=menu-toggle><i class="fa-solid fa-bars fa-fw" aria-hidden=true></i></label><ul class=navigation-list><li class=navigation-item><a class=navigation-link href=/about/>About</a></li><li class=navigation-item><a class=navigation-link href=/posts/>Blog</a></li><li class=navigation-item><a class=navigation-link href=/til/>TIL</a></li><li class=navigation-item><a class=navigation-link href=/projects/>Projects</a></li><li class=navigation-item><a class=navigation-link href=/tags/>Tags</a></li></ul></section></nav><div class=content><section class="container post"><article><header><div class=post-title><h1 class=title><a class=title-link href=https://rnemeth90.github.io/posts/2023-08-15-powershell-try-catch/>Using try/catch/finally Blocks in PowerShell</a></h1></div><div class=post-meta><div class=date><span class=posted-on><i class="fa-solid fa-calendar" aria-hidden=true></i>
<time datetime=2023-08-15T00:00:00Z>2023-08-15
</time></span><span class=reading-time><i class="fa-solid fa-clock" aria-hidden=true></i>
4-minute read</span></div><div class=categories><i class="fa-solid fa-folder" aria-hidden=true></i>
<a href=/categories/powershell/>PowerShell</a>
<span class=separator>•</span>
<a href=/categories/devops/>Devops</a>
<span class=separator>•</span>
<a href=/categories/software-development/>Software Development</a></div><div class=tags><i class="fa-solid fa-tag" aria-hidden=true></i>
<span class=tag><a href=/tags/powershell/>PowerShell</a>
</span><span class=separator>•</span>
<span class=tag><a href=/tags/devops/>Devops</a>
</span><span class=separator>•</span>
<span class=tag><a href=/tags/software-development/>Software Development</a></span></div></div></header><div class=post-content><p>Despite being a great language, PowerShell is not impervious to errors. Errors that occur within your code can stop it&rsquo;s execution or even cause unexpected changes in the resources that your script is managing. Learning to handle these errors gracefully is the foundation of defensive coding. Today, we&rsquo;ll take a quick look at how PowerShell handles errors with Try-Catch-Finally blocks. They allow you to gracefully handle errors and perform cleanup operations, ensuring that your script doesn&rsquo;t crash when the unexpected occurs. We&rsquo;ll then cover the differences in terminating and non-terminating errors and why you should take these into consideration when implementing error handling.</p><h2 id=the-try-block>The Try Block
<a class=heading-link href=#the-try-block><i class="fa-solid fa-link" aria-hidden=true title="Link to heading"></i>
<span class=sr-only>Link to heading</span></a></h2><p>The Try block is where you place the code that might generate an error. Think of it as a protective bubble around your potentially troublesome code. If an error occurs within the Try block, PowerShell will immediately jump to the corresponding Catch block.</p><p>Here&rsquo;s a simple example:</p><pre tabindex=0><code>try {
    # Code that might generate an error
    Get-Item -Path &#34;NonexistentFile.txt&#34;
}
catch {
    # Code to handle the error
    Write-Host &#34;An error occurred: $_&#34;
}
</code></pre><h2 id=the-catch-block>The Catch Block
<a class=heading-link href=#the-catch-block><i class="fa-solid fa-link" aria-hidden=true title="Link to heading"></i>
<span class=sr-only>Link to heading</span></a></h2><p>The Catch block is where you can handle the error. PowerShell provides you with a special variable $_ that contains information about the error. You can use this variable to display error messages or even take corrective actions.</p><p>In the example above, we&rsquo;re capturing the error generated by attempting to retrieve a nonexistent file. The $_ variable holds the error message, which we&rsquo;re displaying using Write-Host.</p><h2 id=the-finally-block>The Finally Block
<a class=heading-link href=#the-finally-block><i class="fa-solid fa-link" aria-hidden=true title="Link to heading"></i>
<span class=sr-only>Link to heading</span></a></h2><p>Now, let&rsquo;s talk about the unsung hero – the Finally block. This block is executed regardless of whether an error occurred or not. It&rsquo;s where you can place cleanup code that ensures your script leaves no trace behind, even in the face of adversity. Some tasks that are commonly done in the finally block are closing database connections, removing temp files, etc. The finally block is completely optional.</p><pre tabindex=0><code>
try {
    # Code that might generate an error
    # ...
}
catch {
    # Code to handle the error
    # ...
}
finally {
    # Cleanup code here
    # ...
}
</code></pre><h2 id=terminatingnon-terminating-errors>Terminating/non-terminating Errors
<a class=heading-link href=#terminatingnon-terminating-errors><i class="fa-solid fa-link" aria-hidden=true title="Link to heading"></i>
<span class=sr-only>Link to heading</span></a></h2><p>non-terminating errors are any error that will not stop the execution of your script. Most cmdlets in PowerShell are non-terminating. They may output an error, but your script will continue to run. These kinds of errors cannot be caught with a catch block by default. The reason for this is the default <code>ErrorAction</code> in your PowerShell profile, which is set to <code>Continue</code>.</p><pre tabindex=0><code># To show your default error action type
$ErrorActionPreference
</code></pre><p>Let&rsquo;s go back and look at our first example:</p><pre tabindex=0><code>try {
    # Code that might generate an error
    Get-Item -Path &#34;NonexistentFile.txt&#34;
}
catch {
    # Code to handle the error
    Write-Host &#34;An error occurred: $_&#34;
}
</code></pre><p>If you took the time to run this code, you may have noticed that the <code>Write-Host</code> cmdlet in the <code>catch</code> block was never ran. Why did we get a red error message in our PowerShell console, rather than the text <code>An error occurred: ...</code>? The reason is that the non-existing path isn&rsquo;t a terminating error, and the default <code>ErrorAction</code> is <code>Continue</code>. To catch the error, you will need to change the <code>ErrorAction</code> in your PowerShell console to <code>Stop</code>. This can be done in multiple ways. You can add <code>-ErrorAction Stop</code> to the cmdlet, like this:</p><pre tabindex=0><code>try {
    # Code that might generate an error
    Get-Item -Path &#34;NonexistentFile.txt&#34; -ErrorAction Stop
}
catch {
    # Code to handle the error
    Write-Host &#34;An error occurred: $_&#34;
}
</code></pre><p>Or you can change the <code>ErrorActionPreference</code> for the entire script, by adding this to the top of the script:</p><pre tabindex=0><code>$ErrorActionPreference = &#34;Stop&#34;
</code></pre><h2 id=exceptions>Exceptions
<a class=heading-link href=#exceptions><i class="fa-solid fa-link" aria-hidden=true title="Link to heading"></i>
<span class=sr-only>Link to heading</span></a></h2><p>If you have ever worked with exceptions in C# you can skip this section. In the previous examples, we used simple <code>catch</code> blocks that will catch <em>any</em> error. This is a good start, but we can do better. PowerShell allows you to catch individual exceptions based on the exception type, similar to how C# handles catching exceptions.</p><p>Let&rsquo;s look at an example:</p><pre tabindex=0><code>try {
    # Attempt to open a non-existent file
    $file = Get-Content -Path &#34;NonexistentFile.txt&#34;
}
catch [System.IO.FileNotFoundException] {
    Write-Host &#34;Caught a FileNotFoundException: $_&#34;
}
catch {
    Write-Host &#34;Caught an exception: $_&#34;
}
</code></pre><p>We now have two <code>catch</code> blocks. If we encounter an exception of type <code>System.IO.FileNotFoundException</code>, the first <code>catch</code> block will catch the exception and handle it accordingly. The second <code>catch</code> block will handle any other generic error.</p><h2 id=conclusion>Conclusion
<a class=heading-link href=#conclusion><i class="fa-solid fa-link" aria-hidden=true title="Link to heading"></i>
<span class=sr-only>Link to heading</span></a></h2><p>Error handling might seem daunting at first, but with the power of Try-Catch-Finally blocks at your fingertips, you&rsquo;re well-equipped to handle errors gracefully and ensure the resilience of your PowerShell scripts. Remember, every error is an opportunity to refine your skills and make your scripts more robust.</p><p>Thanks for reading!</p><p>Official Microsoft Documentation for Try-Catch-Finally in PowerShell:
<a href="https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.3" class=external-link target=_blank rel=noopener>about_try_catch_finally</a></p></div><footer></footer></article></section></div><footer class=footer><section class=container>©
2012 -
2025
Ryan Nemeth
·
Powered by <a href=https://gohugo.io/ target=_blank rel=noopener>Hugo</a> & <a href=https://github.com/luizdepra/hugo-coder/ target=_blank rel=noopener>Coder</a>.</section></footer></main><script src=/js/coder.min.6ae284be93d2d19dad1f02b0039508d9aab3180a12a06dcc71b0b0ef7825a317.js integrity="sha256-auKEvpPS0Z2tHwKwA5UI2aqzGAoSoG3McbCw73gloxc="></script></body></html>